# Module manifest for module 'PSTenableSC'
# Generated by: Ramil Rohi
# Generated on: 31.07.2018

@{
# Script module or binary module file associated with this manifest.
RootModule = 'PSTenableSC.psm1'

# Version number of this module.
ModuleVersion = '3.6.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '68ee5af6-9268-4b5d-b86e-6cdc7a12dd07'

# Author of this module
Author = 'Ramil Rohi'

# Company or vendor of this module
# CompanyName = ''

# Copyright statement for this module
Copyright = '2018-2022'

# Description of the functionality provided by this module
Description = 'PowerShell Tenable.SC Module.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('ImportExcel')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @('')

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @('')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'ConvertFrom-SCReportCSV2XLSX',
    'Get-SCActivePluginFeedStatus',
    'Get-SCLicenseStatus',
    'Get-SCPlugin',
    'Get-SCPlugins',
    'Get-SCReports',
    'Get-SCRepositories',
    'Get-SCScanResults',
    'Initialize-SCActivePluginFeedUpdate',
    'Get-SCPluginFamilies',
    'Get-SCLicenseStatus',
    'Get-SCScanZones',
    'Export-SCReport',
    'Get-SCScans',
    'Get-SCAssets',
    'Get-SCPolicies',
    'Get-SCBlackoutWindows',
    'Set-SCScan',
    'Remove-SCAsset',
    'New-SCScan',
    'Get-SCCredentials',
    'Get-SCUsers',
    'New-SCAsset',
    'Start-SCScan',
    'Get-SCScanners',
    'Remove-SCReport',
    'Get-SCAuditFiles',
    'Get-SCReportDefinitions',
    'Remove-SCScan',
    'Stop-SCScan',
    'Copy-SCScan',
    'Suspend-SCScan',
    'Resume-SCScan'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
#CmdletsToExport = ''

# Variables to export from this module
#VariablesToExport = ''

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
#AliasesToExport = ''

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
ModuleList = @('PSTenableSC')

# List of all files packaged with this module
FileList = @('PSTenableSC.psm1','PSTenableSC.psd1','PSTenableSCLocal.psd1','PSTenableSCSupport.ps1','README.md')

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
    PSData = @{
        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/RRohi/PSTenableSC/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/RRohi/PSTenableSC'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '
        1.0.0 - Initial module. Back when I didn''t use PowerShell manifest file to list changes in the module. [2018.07.31]
        3.6.0 - The project ended because I no longer have access to Tenable SC. [2020.01.18]
        3.6.1 - Removed most of the unnecessary capitalizations. Found a bunch of typos and some copy-paste-related accidents. [2022.08.23]
        '
    } # End of PSData hashtable
} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''
}